[package]
name = "BeatBoxer-Tui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
color-eyre = "0.6.5"
crossterm = "0.29.0"
memmap2 = "0.9.9"
log = "0.4.29"
crossbeam-channel = "0.5.15"
